#
# Copyright (c) 2020, 2024, Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: coherence.oracle.com/v1
kind: Coherence
metadata:
  name: payment
spec:
  role: Payment
  replicas: 1
  image: 10.10.10.240/library/ss-payment:2.3.3
  readinessProbe:
    initialDelaySeconds: 10
    periodSeconds: 10
  env:
    - name: TRACING_HOST
      value: "jaeger-collector"
    - name: JAEGER_SAMPLER_TYPE
      value: "const"
    - name: JAEGER_SAMPLER_PARAM
      value: "1"
    - name: JAEGER_SERVICE_NAME
      value: Payment
    - name: JAEGER_ENDPOINT
      value: "http://jaeger-collector:14268/api/traces"
  application:
    type: helidon
  jvm:
    memory:
      heapSize: 2g
    args:
      - "-Dhelidon.serialFilter.ignoreFiles=true" 
      - "-Dhelidon.serialFilter.pattern=*"
      - "-Dhelidon.serialFilter.failure.action=WARN"
  coherence:
    storageEnabled: false
    metrics:
      enabled: true
  ports:
    - name: grpc
      port: 1408
      service:
        name: payment
    - name: http
      port: 7001
      service:
        name: payment-http
        port: 80
      serviceMonitor:
        enabled: true
    - name: metrics
      serviceMonitor:
        enabled: true
