#
# Copyright (c) 2020,2021 Oracle and/or its affiliates.
#
# Licensed under the Universal Permissive License v 1.0 as shown at
# https://oss.oracle.com/licenses/upl.
#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: monitoring-sockshop
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      component: sockshop
  endpoints:
  - port: http
    interval: 30s
  namespaceSelector:
    matchNames:
    - sockshop
